
/*
 * This file was generated by the SOM Compiler.
 * FileName: MNIcon.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

/*
 *   MNIcon class release 1.0 (02/21/93) by Makoto Nagata
 */


#ifndef MNIcon_h
#define MNIcon_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef MNIcon
#define MNIcon SOMAny
#endif
#include "wpicon.h"

#define MNIcon_MajorVersion 1
#define MNIcon_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define MNIconNewClass mniconc
#pragma linkage(mniconc, system)
#define MNIconClassData mnicond
#define MNIconCClassData mniconx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define MNIcon_classObj MNIconClassData.classObject
#define _MNIcon MNIcon_classObj

/*
 * New and Renew macros for MNIcon
 */
#define _MNIconNew() (_somNew(MNIconClassData.classObject))
#define MNIconNew() \
	( MNIconClassData.classObject \
		? _MNIconNew() \
		: ( MNIconNewClass(MNIcon_MajorVersion, MNIcon_MinorVersion), _MNIconNew() ) )
#define MNIconRenew(buf) \
	( _somRenew(MNIconClassData.classObject, buf) )

/*
 * Override method: wpDragOver
 */
#define MNIcon_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)

/*
 * Override method: wpDrop
 */
#define MNIcon_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK MNIconNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(MNIconNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct MNIconClassDataStructure {
	SOMAny *classObject;
} MNIconClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct MNIconCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} MNIconCClassData;

#endif       /* MNIcon_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: MNIcon.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef MNIcon_mh
#define MNIcon_mh


/*
 * Define the class name as an object type
 */
#ifndef M_MNIcon
#define M_MNIcon SOMAny
#endif

#define M_MNIcon_MajorVersion 1
#define M_MNIcon_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_MNIconNewClass mniconc
#pragma linkage(mniconc, system)
#define M_MNIconClassData mnicond
#define M_MNIconCClassData mniconx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_MNIcon_classObj M_MNIconClassData.classObject
#define _M_MNIcon M_MNIcon_classObj

/*
 * New and Renew macros for M_MNIcon
 */
#define _M_MNIconNew() (_somNew(M_MNIconClassData.classObject))
#define M_MNIconNew() \
	( M_MNIconClassData.classObject \
		? _M_MNIconNew() \
		: ( M_MNIconNewClass(M_MNIcon_MajorVersion, M_MNIcon_MinorVersion), _M_MNIconNew() ) )
#define M_MNIconRenew(buf) \
	( _somRenew(M_MNIconClassData.classObject, buf) )

/*
 * Override method: wpclsQueryTitle
 */
#define M_MNIcon_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_MNIconNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_MNIconNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_MNIconClassDataStructure {
	SOMAny *classObject;
} M_MNIconClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_MNIconCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_MNIconCClassData;

#endif       /* MNIcon_h */
